### ISSUE TITLE
Not getting file on path https://dl.dropboxusercontent.com/u/38822310/DemoDir.zip

### ISSUE THREAD

**Issue by sarishti** [cocoa-ai/FacesVisionDemo#1]
On ./download.sh getting error

Resolving dl.dropboxusercontent.com... 162.125.81.6, 2620:100:6031:6::a27d:5106
Connecting to dl.dropboxusercontent.com|162.125.81.6|:443... connected.
WARNING: cannot verify dl.dropboxusercontent.com's certificate, issued by ‘emailAddress=support@fortinet.com,CN=FGT5HD3917800279,OU=Certificate Authority,O=Fortinet,L=Sunnyvale,ST=California,C=US’:
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 404 Not Found
2017-09-14 11:43:59 ERROR 404: Not Found.

When I checked then file is not available on path

**Comment by vadymmarkov** [comment]
Yes, it seems like files were moved to Google Drive. I've added a description how to download model and deploy.prototxt manually  https://github.com/cocoa-ai/FacesVisionDemo/pull/2
